# Declaração da função de mostrar_menu, apenas a parte visual
def mostrar_menu():
    print('|' + '-' * 70 + '|')
    print('|' + ' Menu de conversão de base:'.ljust(70) + '|')
    print('|' + '-' * 70 + '|')
    print('| 1. Decimal -> Binario'.ljust(71) + '|')
    print('| 2. Binario -> Decimal'.ljust(71) + '|')
    print('| 3. Decimal -> Octal'.ljust(71) + '|')
    print('| 4. Octal -> Decimal'.ljust(71) + '|')
    print('| 5. Decimal -> Hexadecimal'.ljust(71) + '|')
    print('| 6. Hexadecimal -> Decimal'.ljust(71) + '|')
    print('| 7. Binario -> Octal'.ljust(71) + '|')
    print('| 8. Octal -> Binario'.ljust(71) + '|')
    print('| 9. Binario -> Hexadecimal'.ljust(71) + '|')
    print('| 10.Hexadecimal -> Binario'.ljust(71) + '|')
    print('| 11. Octal -> Hexadecimal'.ljust(71) + '|')
    print('| 12. Hexadecimal -> Octal'.ljust(71) + '|')
    print('|' + '-' * 70 + '|')
    print('| 0. Sair'.ljust(71) + '|')
    print('|' + '-' * 70 + '|')
